export const imagespath = {
app_log : require('../assets/Images/app_logo.png'),
Adpik : require('../assets/Images/Adpik.png'),
good_mor : require('../assets/Images/good_mor.png'),
download_icon : require('../assets/Images/download.png'),
edit_icon : require('../assets/Images/edit.png'),
whatsapp_icon : require('../assets/Images/whatsapp.png'),
profile_icon : require('../assets/Images/Ellipse.png'),
like_icon : require('../assets/Images/like.png'),
like_without_icon : require('../assets/Images/like_without.png'),
like_without_icon : require('../assets/Images/like_without.png'),
comment_icon : require('../assets/Images/comment.png'),
close_icon : require('../assets/Images/close.png'),
gallary : require('../assets/Images/gellary.png'),
info_help : require('../assets/Images/Info_help.png'),
log_out : require('../assets/Images/logout-circle-line.png'),
info : require('../assets/Images/Info.png'),
arrow_Grey : require('../assets/Images/arrow_grey.png'),
bottom_home : require('../assets/Images/HomeBottom.png'),
chat_bottom : require('../assets/Images/chat.png'),
create_post : require('../assets/Images/create_post.png'),
profile_bottom : require('../assets/Images/Profile.png'),
help_bottom : require('../assets/Images/help.png'),
back_arrow : require('../assets/Images/back_arrow.png'),
gellary_pop : require('../assets/Images/gellary_pop.png'),
video_pop : require('../assets/Images/videocam.png'),
}