import { Dimensions, StyleSheet } from "react-native";
import { Colors, fonts } from "../../../theme/Colors";
const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.BG_COLOR,
  },
  content: {
    paddingVertical: 12,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  logo: {
    width: 120,
    height: 40,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  iconPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#ffdfe6",
    marginRight: 10,
  },
  avatarPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#ffdfe6",
  },
  avatarImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },

  /* Categories chips */
  categoriesWrap: {
    marginTop: 6,
    marginHorizontal: 0,
    paddingHorizontal: 8,
  },
  categoriesScroll: {
    paddingHorizontal: 12,
    alignItems: "center",
  },
  categoriesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    marginHorizontal: 6,
    borderWidth: 0,
    backgroundColor: "#E1F4FF",
    justifyContent: "center",
    minHeight: 36,
    alignItems: "center",
  },
  chipSelected: {
    backgroundColor: Colors.BUTTON_COLOR,
    borderRadius: 20,
  },
  chipUnselected: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ff5aa5",
    borderRadius: 20,
  },
  chipText: {
    color: "#ff5aa5",
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_12,
  },
  chipTextSelected: {
    color: Colors.WHITE,
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_12,
  },

  card: {
    // margin: 16,
    marginHorizontal: 16,
    marginTop: 14,
    backgroundColor: "#fff",
    borderRadius: 12,
    overflow: "hidden",
    elevation: 2,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 8,
    backgroundColor: "#f5f5f5",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  profileAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: fonts.font_size_14,
    fontFamily: fonts.robot_bold,
    color: Colors.BLACK,
  },
  profileHandle: {
    fontSize: fonts.font_size_12,
    fontFamily: fonts.robot_regular,
    color: "#999",
    marginTop: 2,
  },
  cardImage: {
   
    // height: (width - 32) * 0.56,
    width: "100%",
    height: undefined,
    aspectRatio: 3 / 4,
  },
  cardImageInner: {
    borderRadius: 0,
  },
  frameContainer: {
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 0,
    borderRadius: 0,
    overflow: "hidden",
    alignSelf: "stretch",
  },
  frameVariantPink: {
    borderWidth: 5,
    borderColor: "#FF2D81",
    backgroundColor: "#FFE5F1",
  },
  frameVariantBlue: {
    borderWidth: 5,
    borderColor: "#006DFF",
    backgroundColor: "#E0EDFF",
  },
  frameVariantGold: {
    borderWidth: 5,
    borderColor: "#FFAA00",
    backgroundColor: "#FFF3D9",
  },
  userInfoOverlay: {
    position: "absolute",
    right: 8,
    bottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "rgba(0, 0, 0, 0.55)",
  },
  userInfoName: {
    color: Colors.WHITE,
    fontFamily: fonts.robot_bold,
    fontSize: fonts.font_size_12,
  },
  userInfoMobile: {
    color: Colors.WHITE,
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_11 || 11,
    marginTop: 2,
  },
  postTitleWrap: {
    width: "100%",
    alignItems: "center",
    marginTop: 24,
  },
  postTitleText: {
    color: "#FF2D81",
    fontFamily: fonts.robot_bold,
    fontSize: fonts.font_size_24 || 24,
    textShadowColor: "rgba(0, 0, 0, 0.25)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  postBottomStrip: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "rgba(255, 255, 255, 0.96)",
  },
  postBottomStripPink: {
    borderTopWidth: 2,
    borderTopColor: "#FF2D81",
  },
  postBottomStripBlue: {
    borderTopWidth: 2,
    borderTopColor: "#2B7BD3",
  },
  postBottomStripPurple: {
    borderTopWidth: 0,
    borderTopColor: "transparent",
    backgroundColor: "rgba(255, 245, 255, 0.98)",
  },
  postBottomTextArea: {
    flex: 1,
    paddingRight: 100,
  },
  postBottomName: {
    fontFamily: fonts.robot_bold,
    fontSize: fonts.font_size_14,
    color: Colors.BLACK,
  },
  postBottomNamePink: {
    color: "#FF2D81",
  },
  postBottomNameBlue: {
    color: "#2B7BD3",
  },
  postBottomNamePurple: {
    color: "#3F1E7A",
  },
  postBottomTagline: {
    marginTop: 2,
    fontFamily: fonts.robot_regular,
    fontSize: fonts.font_size_12,
    color: "#444",
  },
  postBottomMobile: {
    marginTop: 2,
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_12,
    color: "#111",
  },
  variant2BottomRow: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 18,
    alignItems: "center",
    paddingHorizontal: 16,
  },
  variant2TextCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.96)",
    width: "100%",
  },
  variant2TextArea: {
    flex: 1,
    marginRight: 12,
  },
  variant2Tagline: {
    marginTop: 2,
    fontFamily: fonts.robot_regular,
    fontSize: fonts.font_size_12,
    color: "#333",
  },
  variant2Mobile: {
    marginTop: 2,
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_12,
    color: "#2B7BD3",
  },
  variant2RightImage: {
    width: 70,
    height: 80,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#2B7BD3",
  },
  postUserRow: {
    position: "absolute",
    left: 14,
    bottom: 14,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  postUserAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 2,
    borderColor: "#ffffff",
  },
  postUserTextWrap: {
    justifyContent: "center",
  },
  postUserName: {
    color: Colors.WHITE,
    fontFamily: fonts.robot_bold,
    fontSize: fonts.font_size_13 || 13,
  },
  postUserMobile: {
    color: Colors.WHITE,
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_11 || 11,
    marginTop: 2,
  },
  postPhotoCard: {
    position: "absolute",
    right: 18,
    bottom: 26,
    width: 92,
    height: 112,
    borderRadius: 18,
    borderWidth: 3,
    borderColor: "#ffffff",
    backgroundColor: "#000",
    overflow: "hidden",
  },
  postPhotoCardPink: {
    borderColor: "#FF2D81",
  },
  postPhotoCardBlue: {
    borderColor: "#2B7BD3",
  },
  postPhotoCardPurple: {
    borderColor: "#8B3CF9",
  },
  variant3Strip: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginHorizontal: 0,
    borderRadius: 0,
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  variant3StripAvatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 2,
    borderColor: "#ffffff",
    marginRight: 12,
    backgroundColor: "#000",
  },
  variant3StripText: {
    flex: 1,
  },
  variant3StripTagline: {
    marginTop: 2,
    fontFamily: fonts.robot_regular,
    fontSize: fonts.font_size_12,
    color: "#222",
  },
  variant3StripMobile: {
    marginTop: 2,
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_12,
    color: "#3F1E7A",
  },
  cardBody: {
    padding: 12,
  },
  cardTitle: {
    fontSize: fonts.font_size_26,
    fontFamily: fonts.robot_bold,
    color: Colors.BLACK,
    marginBottom: 6,
  },
  cardSubtitle: {
    fontSize: fonts.font_size_14,
    fontFamily: fonts.robot_regular,
    color: "#6b6b6b",
    marginBottom: 10,
  },
  actionRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginBottom: 12,
  },
  metric: {
    marginRight: 20,
  },
  metricContent: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  metricIcon: {
    width: 17,
    height: 17,
    marginRight: 6,
  },
  metricCount: {
    fontSize: fonts.font_size_14,
    fontFamily: fonts.robot_medium,
    color: Colors.BLACK,
  },

  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  pill: {
    flex: 1,
    paddingVertical: 8,
    marginHorizontal: 4,
    borderRadius: 20,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  pillIcon: {
    width: 18,
    height: 18,
    marginRight: 6,
    tintColor: Colors.WHITE,
  },
  pillText: {
    color: Colors.WHITE,
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_12,
  },

  // Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: "90%",
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  modalTitle: {
    fontSize: fonts.font_size_18,
    fontFamily: fonts.robot_bold,
    color: Colors.BLACK,
  },
  closeIcon: {
    width: 24,
    height: 24,
    tintColor: Colors.BUTTON_COLOR,
  },
  commentsList: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  commentItem: {
    flexDirection: "row",
    marginBottom: 16,
    paddingRight: 8,
  },
  commentAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  commentBody: {
    flex: 1,
    backgroundColor: "#f5f5f5",
    borderRadius: 12,
    padding: 12,
  },
  commentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  commentName: {
    fontSize: fonts.font_size_14,
    fontFamily: fonts.robot_bold,
    color: Colors.BLACK,
  },
  commentDate: {
    fontSize: fonts.font_size_12,
    fontFamily: fonts.robot_regular,
    color: "#999",
  },
  commentText: {
    fontSize: fonts.font_size_13,
    fontFamily: fonts.robot_regular,
    color: "#333",
    lineHeight: 18,
  },
  commentInputContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#e0e0e0",
    alignItems: "center",
  },
  commentInput: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#f5f5f5",
    paddingHorizontal: 16,
    fontSize: fonts.font_size_14,
    fontFamily: fonts.robot_regular,
    marginRight: 12,
    color: Colors.BLACK,
  },
  postButton: {
    backgroundColor: Colors.BUTTON_COLOR,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 22,
  },
  postButtonText: {
    color: Colors.WHITE,
    fontFamily: fonts.robot_bold,
    fontSize: fonts.font_size_14,
  },
});


export default styles;