import { Dimensions, StyleSheet } from 'react-native';
import { Colors, fonts } from '../../../theme/Colors';

const width = Dimensions.get('window').width;


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.BG_COLOR,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 20,
    paddingTop: 16,
  },
  headingText: {
    fontSize: fonts.font_size_15 || 15,
    fontFamily: fonts.robot_semi_bold,
    color: Colors.black,
    // marginBottom: 10,
    fontWeight: '500',
  },
  previewCard: {
    width: width - 32,
    alignSelf: 'center',
    borderRadius: 20,
    backgroundColor: Colors.WHITE,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#d0d0d0',
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 5,
    marginVertical: 12,
  },
  selectedPreview: {
    borderWidth: 3,
    borderColor: Colors.primary,
  },
  cardImage: {
    // HomeScreen ke jaise hi aspect ratio
    width: '100%',
    height: undefined,
    aspectRatio: 3 / 4,
  },
  cardImageInner: {
    borderRadius: 0,
  },
  postTitleWrap: {
    width: '100%',
    alignItems: 'center',
    marginTop: 24,
  },
  postTitleText: {
    color: '#FF2D81',
    fontFamily: fonts.robot_bold,
    fontSize: fonts.font_size_24 || 24,
    textShadowColor: 'rgba(150, 150, 150, 0.12)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  postBottomStrip: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
  },
  postBottomStripPink: {
    borderTopWidth: 2,
    borderTopColor: '#FF2D81',
  },
  postBottomStripBlue: {
    borderTopWidth: 2,
    borderTopColor: '#2B7BD3',
  },
  postBottomStripPurple: {
    borderTopWidth: 0,
    borderTopColor: 'transparent',
    backgroundColor: 'rgba(255, 245, 255, 0.98)',
  },
  postBottomTextArea: {
    flex: 1,
    paddingRight: 100,
  },
  postBottomName: {
    fontFamily: fonts.robot_bold,
    fontSize: fonts.font_size_14,
    color: Colors.BLACK,
  },
  postBottomNamePink: {
    color: '#FF2D81',
  },
  postBottomNameBlue: {
    color: '#2B7BD3',
  },
  postBottomNamePurple: {
    color: '#3F1E7A',
  },
  postBottomTagline: {
    marginTop: 2,
    fontFamily: fonts.robot_regular,
    fontSize: fonts.font_size_12,
    color: '#444',
  },
  postBottomMobile: {
    marginTop: 2,
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_12,
    color: '#111',
  },
  variant2BottomRow: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 18,
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  variant2TextCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    width: '100%',
  },
  variant2TextArea: {
    flex: 1,
    marginRight: 12,
  },
  variant2Tagline: {
    marginTop: 2,
    fontFamily: fonts.robot_regular,
    fontSize: fonts.font_size_12,
    color: '#333',
  },
  variant2Mobile: {
    marginTop: 2,
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_12,
    color: '#2B7BD3',
  },
  variant2RightImage: {
    width: 70,
    height: 80,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#2B7BD3',
  },
  variant3Strip: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginHorizontal: 0,
    borderRadius: 0,
    elevation: 3,
    shadowColor: '#d0d0d0',
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  variant3StripAvatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 2,
    borderColor: '#ffffff',
    marginRight: 12,
  },
  variant3StripText: {
    flex: 1,
    justifyContent: 'center',
  },
  variant3StripTagline: {
    marginTop: 2,
    fontFamily: fonts.robot_regular,
    fontSize: fonts.font_size_12,
    color: '#444',
  },
  variant3StripMobile: {
    marginTop: 2,
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_12,
    color: '#8B3CF9',
  },
  bottomBar: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    paddingBottom: 10,
    backgroundColor: Colors.BG_COLOR,
    borderTopWidth: 1,
    borderTopColor: Colors.light_gray,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bottomBarContent: {
    alignItems: 'center',
    gap: 14,
    // width: "100%",
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  selectedLabel: {
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_14 || 14,
    color: Colors.black,
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    width: '100%',
  },
  actionButton: {
    // flex: 1,
    paddingHorizontal: 0,
  },
  confirmButton: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: Colors.primary,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#cccccc',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    width: '30%',
  },
  confirmButtonText: {
    fontFamily: fonts.robot_semi_bold,
    fontSize: fonts.font_size_12 || 12,
    color: Colors.WHITE,
    fontWeight: '600',
  },
  createPostButton: {
    // flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: '#ff5aa5',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',

    width: '50%',
  },
  createPostButtonText: {
    fontFamily: fonts.robot_semi_bold,
    fontSize: fonts.font_size_12 || 12,
    color: Colors.WHITE,
    fontWeight: '600',
  },
  designControls: {
    marginVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  arrowButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2.5,
    borderColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.WHITE,
    elevation: 3,
    shadowColor: '#d0d0d0',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 4,
  },
  arrowText: {
    fontSize: 24,
    color: Colors.primary,
  },
  designCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  dotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#e0e0e0',
    marginHorizontal: 6,
  },
  dotActive: {
    backgroundColor: Colors.primary,
    width: 18,
  },
  designCounterText: {
    fontFamily: fonts.robot_medium,
    fontSize: fonts.font_size_13 || 13,
    color: Colors.black,
    fontWeight: '500',
  },
  changeButton: {
    alignSelf: 'center',
    marginTop: 16,
    marginBottom: 12,
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: Colors.primary,
    backgroundColor: Colors.WHITE,
    elevation: 3,
    shadowColor: '#cccccc',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 4,
  },
  changeButtonLabel: {
    fontFamily: fonts.robot_semi_bold,
    fontSize: fonts.font_size_14 || 14,
    color: Colors.primary,
    fontWeight: '600',
  },
});

export default styles;